image: node:lts

variables:
  npm_config_fetch_retry_maxtimeout: 600000

pages:
  stage: deploy
  script:
    - git submodule update --init --remote --recursive
    - npm ci
    - npm run build
    - rm -rf public
    - mv dist public
    - cp -r AxMirrors public  
  artifacts:
    paths:
      - public
  only:
    - main
