image: node:lts

variables:
  GIT_SUBMODULE_STRATEGY: none

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - rm -rf public
    - mv dist public
  
  artifacts:
    paths:
      - public
  only:
    - main
