image: node:lts

variables:
  GIT_SUBMODULE_STRATEGY: none

pages:
  stage: deploy
  script:
    - git submodule update --init --depth 1 vendor/axmirrors

    - npm ci
    - npm run build
    - rm -rf public
    - mv dist public

    - mkdir -p public/axmirrors
    - cp -r vendor/axmirrors/* public/AxMirrors/
    - rm -rf public/AxMirrors/.git
  
  artifacts:
    paths:
      - public
  only:
    - main